name: Build, Scan and Push Image to ghcr

on:
  push:
    branches: [main]

jobs:
  build-scan-push-pgcron:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/${{ github.repository }}/cloudnative-pg-cron
          tags: ${{ github.sha }}
          containerfiles: |
            ./cnpg-pgcron/Dockerfile

      - name: activate podman socket
        run:  systemctl --user start podman.socket

      - name: Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ghcr.io/${{ github.repository }}/cloudnative-pg-cron:${{ github.sha }}
          format: 'table'
          severity: 'HIGH,CRITICAL'

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: cloudnative-pg-cron
          tags: ${{ github.sha }} 18.1-system-trixie
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
